// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// loglikelihood_ultrafast
double loglikelihood_ultrafast(const NumericMatrix& y, const NumericVector& first, const NumericMatrix& combins, const NumericMatrix& s, const NumericMatrix& e, const NumericMatrix& i, const NumericMatrix& lambda, const NumericMatrix& epsilon1, const NumericMatrix& epsilon2, const NumericMatrix& epsilon3, const NumericVector& mixing_prop, const NumericVector& probs1, const NumericVector& probs2, const NumericVector& counts, int L);
RcppExport SEXP _overcoverage2_loglikelihood_ultrafast(SEXP ySEXP, SEXP firstSEXP, SEXP combinsSEXP, SEXP sSEXP, SEXP eSEXP, SEXP iSEXP, SEXP lambdaSEXP, SEXP epsilon1SEXP, SEXP epsilon2SEXP, SEXP epsilon3SEXP, SEXP mixing_propSEXP, SEXP probs1SEXP, SEXP probs2SEXP, SEXP countsSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type combins(combinsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type e(eSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type i(iSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type epsilon1(epsilon1SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type epsilon2(epsilon2SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type epsilon3(epsilon3SEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type mixing_prop(mixing_propSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probs1(probs1SEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type probs2(probs2SEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(loglikelihood_ultrafast(y, first, combins, s, e, i, lambda, epsilon1, epsilon2, epsilon3, mixing_prop, probs1, probs2, counts, L));
    return rcpp_result_gen;
END_RCPP
}
// loglikelihood_cpp
double loglikelihood_cpp(const arma::mat& y, const arma::vec& first, const arma::mat& combins, const arma::mat& s, const arma::mat& e, const arma::mat& i, const arma::mat& lambda, const arma::mat& epsilon1, const arma::mat& epsilon2, const arma::mat& epsilon3, const arma::vec& mixing_prop, const arma::vec& probs1, const arma::vec& probs2, const arma::vec& counts, int L);
RcppExport SEXP _overcoverage2_loglikelihood_cpp(SEXP ySEXP, SEXP firstSEXP, SEXP combinsSEXP, SEXP sSEXP, SEXP eSEXP, SEXP iSEXP, SEXP lambdaSEXP, SEXP epsilon1SEXP, SEXP epsilon2SEXP, SEXP epsilon3SEXP, SEXP mixing_propSEXP, SEXP probs1SEXP, SEXP probs2SEXP, SEXP countsSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type combins(combinsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type e(eSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type i(iSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type epsilon1(epsilon1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type epsilon2(epsilon2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type epsilon3(epsilon3SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mixing_prop(mixing_propSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type probs1(probs1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type probs2(probs2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(loglikelihood_cpp(y, first, combins, s, e, i, lambda, epsilon1, epsilon2, epsilon3, mixing_prop, probs1, probs2, counts, L));
    return rcpp_result_gen;
END_RCPP
}
// loglikelihood_fast_cpp
double loglikelihood_fast_cpp(const arma::mat& y, const arma::vec& first, const arma::mat& combins, const arma::mat& s, const arma::mat& e, const arma::mat& i, const arma::mat& lambda, const arma::mat& epsilon1, const arma::mat& epsilon2, const arma::mat& epsilon3, const arma::vec& mixing_prop, const arma::vec& probs1, const arma::vec& probs2, const arma::vec& counts, int L);
RcppExport SEXP _overcoverage2_loglikelihood_fast_cpp(SEXP ySEXP, SEXP firstSEXP, SEXP combinsSEXP, SEXP sSEXP, SEXP eSEXP, SEXP iSEXP, SEXP lambdaSEXP, SEXP epsilon1SEXP, SEXP epsilon2SEXP, SEXP epsilon3SEXP, SEXP mixing_propSEXP, SEXP probs1SEXP, SEXP probs2SEXP, SEXP countsSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type combins(combinsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type e(eSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type i(iSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type epsilon1(epsilon1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type epsilon2(epsilon2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type epsilon3(epsilon3SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mixing_prop(mixing_propSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type probs1(probs1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type probs2(probs2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(loglikelihood_fast_cpp(y, first, combins, s, e, i, lambda, epsilon1, epsilon2, epsilon3, mixing_prop, probs1, probs2, counts, L));
    return rcpp_result_gen;
END_RCPP
}
// loglikelihood_BLB_parallel
double loglikelihood_BLB_parallel(const arma::mat& y, const arma::mat& covariates, const arma::mat& age2, const arma::mat& age3, const arma::mat& age4, const arma::mat& tin2, const arma::mat& tin3, const arma::mat& X, const arma::vec& initial, const arma::vec& first, int L, const arma::mat& combins, unsigned int& n, NumericVector& proportions, const arma::vec& params);
RcppExport SEXP _overcoverage2_loglikelihood_BLB_parallel(SEXP ySEXP, SEXP covariatesSEXP, SEXP age2SEXP, SEXP age3SEXP, SEXP age4SEXP, SEXP tin2SEXP, SEXP tin3SEXP, SEXP XSEXP, SEXP initialSEXP, SEXP firstSEXP, SEXP LSEXP, SEXP combinsSEXP, SEXP nSEXP, SEXP proportionsSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type covariates(covariatesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age2(age2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age3(age3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age4(age4SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tin2(tin2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tin3(tin3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type initial(initialSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type combins(combinsSEXP);
    Rcpp::traits::input_parameter< unsigned int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type proportions(proportionsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(loglikelihood_BLB_parallel(y, covariates, age2, age3, age4, tin2, tin3, X, initial, first, L, combins, n, proportions, params));
    return rcpp_result_gen;
END_RCPP
}
// loglikelihood_BLB_parallel_legacy
double loglikelihood_BLB_parallel_legacy(const arma::mat& y, const arma::mat& covariates, const arma::mat& age2, const arma::mat& age3, const arma::mat& age4, const arma::mat& tin2, const arma::mat& tin3, const arma::mat& X, const arma::vec& initial, const arma::vec& first, int L, const arma::mat& combins, unsigned int& n, NumericVector& proportions, const arma::vec& params);
RcppExport SEXP _overcoverage2_loglikelihood_BLB_parallel_legacy(SEXP ySEXP, SEXP covariatesSEXP, SEXP age2SEXP, SEXP age3SEXP, SEXP age4SEXP, SEXP tin2SEXP, SEXP tin3SEXP, SEXP XSEXP, SEXP initialSEXP, SEXP firstSEXP, SEXP LSEXP, SEXP combinsSEXP, SEXP nSEXP, SEXP proportionsSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type covariates(covariatesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age2(age2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age3(age3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age4(age4SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tin2(tin2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tin3(tin3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type initial(initialSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type combins(combinsSEXP);
    Rcpp::traits::input_parameter< unsigned int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type proportions(proportionsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(loglikelihood_BLB_parallel_legacy(y, covariates, age2, age3, age4, tin2, tin3, X, initial, first, L, combins, n, proportions, params));
    return rcpp_result_gen;
END_RCPP
}
// loglikelihood_nonBLB_parallel
double loglikelihood_nonBLB_parallel(const arma::mat& y, const arma::mat& covariates, const arma::mat& age2, const arma::mat& age3, const arma::mat& age4, const arma::mat& tin2, const arma::mat& tin3, const arma::mat& X, const arma::vec& initial, const arma::vec& first, int L, const arma::mat& combins, const arma::vec& params);
RcppExport SEXP _overcoverage2_loglikelihood_nonBLB_parallel(SEXP ySEXP, SEXP covariatesSEXP, SEXP age2SEXP, SEXP age3SEXP, SEXP age4SEXP, SEXP tin2SEXP, SEXP tin3SEXP, SEXP XSEXP, SEXP initialSEXP, SEXP firstSEXP, SEXP LSEXP, SEXP combinsSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type covariates(covariatesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age2(age2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age3(age3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age4(age4SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tin2(tin2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tin3(tin3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type initial(initialSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type combins(combinsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(loglikelihood_nonBLB_parallel(y, covariates, age2, age3, age4, tin2, tin3, X, initial, first, L, combins, params));
    return rcpp_result_gen;
END_RCPP
}
// loglikelihood_nonBLB_parallel_legacy
double loglikelihood_nonBLB_parallel_legacy(const arma::mat& y, const arma::mat& covariates, const arma::mat& age2, const arma::mat& age3, const arma::mat& age4, const arma::mat& tin2, const arma::mat& tin3, const arma::mat& X, const arma::vec& initial, const arma::vec& first, int L, const arma::mat& combins, const arma::vec& params);
RcppExport SEXP _overcoverage2_loglikelihood_nonBLB_parallel_legacy(SEXP ySEXP, SEXP covariatesSEXP, SEXP age2SEXP, SEXP age3SEXP, SEXP age4SEXP, SEXP tin2SEXP, SEXP tin3SEXP, SEXP XSEXP, SEXP initialSEXP, SEXP firstSEXP, SEXP LSEXP, SEXP combinsSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type covariates(covariatesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age2(age2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age3(age3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age4(age4SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tin2(tin2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tin3(tin3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type initial(initialSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type combins(combinsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(loglikelihood_nonBLB_parallel_legacy(y, covariates, age2, age3, age4, tin2, tin3, X, initial, first, L, combins, params));
    return rcpp_result_gen;
END_RCPP
}
// loglikelihood_nonBLB_parallel_legacy_debug
Rcpp::List loglikelihood_nonBLB_parallel_legacy_debug(const arma::mat& y, const arma::mat& covariates, const arma::mat& age2, const arma::mat& age3, const arma::mat& age4, const arma::mat& tin2, const arma::mat& tin3, const arma::mat& X, const arma::vec& initial, const arma::vec& first, int L, const arma::mat& combins, const arma::vec& params);
RcppExport SEXP _overcoverage2_loglikelihood_nonBLB_parallel_legacy_debug(SEXP ySEXP, SEXP covariatesSEXP, SEXP age2SEXP, SEXP age3SEXP, SEXP age4SEXP, SEXP tin2SEXP, SEXP tin3SEXP, SEXP XSEXP, SEXP initialSEXP, SEXP firstSEXP, SEXP LSEXP, SEXP combinsSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type covariates(covariatesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age2(age2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age3(age3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age4(age4SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tin2(tin2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tin3(tin3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type initial(initialSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type combins(combinsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(loglikelihood_nonBLB_parallel_legacy_debug(y, covariates, age2, age3, age4, tin2, tin3, X, initial, first, L, combins, params));
    return rcpp_result_gen;
END_RCPP
}
// loglikelihood_nonBLB_input_debug
Rcpp::List loglikelihood_nonBLB_input_debug(SEXP y, SEXP covariates, SEXP age2, SEXP age3, SEXP age4, SEXP tin2, SEXP tin3, SEXP X, SEXP initial, SEXP first, SEXP combins, SEXP params);
RcppExport SEXP _overcoverage2_loglikelihood_nonBLB_input_debug(SEXP ySEXP, SEXP covariatesSEXP, SEXP age2SEXP, SEXP age3SEXP, SEXP age4SEXP, SEXP tin2SEXP, SEXP tin3SEXP, SEXP XSEXP, SEXP initialSEXP, SEXP firstSEXP, SEXP combinsSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type covariates(covariatesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type age2(age2SEXP);
    Rcpp::traits::input_parameter< SEXP >::type age3(age3SEXP);
    Rcpp::traits::input_parameter< SEXP >::type age4(age4SEXP);
    Rcpp::traits::input_parameter< SEXP >::type tin2(tin2SEXP);
    Rcpp::traits::input_parameter< SEXP >::type tin3(tin3SEXP);
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< SEXP >::type initial(initialSEXP);
    Rcpp::traits::input_parameter< SEXP >::type first(firstSEXP);
    Rcpp::traits::input_parameter< SEXP >::type combins(combinsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(loglikelihood_nonBLB_input_debug(y, covariates, age2, age3, age4, tin2, tin3, X, initial, first, combins, params));
    return rcpp_result_gen;
END_RCPP
}
// loglikelihood_nonBLB_deep_debug
Rcpp::List loglikelihood_nonBLB_deep_debug(SEXP y, SEXP age2, SEXP age3, SEXP age4, SEXP tin2, SEXP tin3, SEXP first, SEXP combins, int L);
RcppExport SEXP _overcoverage2_loglikelihood_nonBLB_deep_debug(SEXP ySEXP, SEXP age2SEXP, SEXP age3SEXP, SEXP age4SEXP, SEXP tin2SEXP, SEXP tin3SEXP, SEXP firstSEXP, SEXP combinsSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type age2(age2SEXP);
    Rcpp::traits::input_parameter< SEXP >::type age3(age3SEXP);
    Rcpp::traits::input_parameter< SEXP >::type age4(age4SEXP);
    Rcpp::traits::input_parameter< SEXP >::type tin2(tin2SEXP);
    Rcpp::traits::input_parameter< SEXP >::type tin3(tin3SEXP);
    Rcpp::traits::input_parameter< SEXP >::type first(firstSEXP);
    Rcpp::traits::input_parameter< SEXP >::type combins(combinsSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(loglikelihood_nonBLB_deep_debug(y, age2, age3, age4, tin2, tin3, first, combins, L));
    return rcpp_result_gen;
END_RCPP
}
// loglikelihood_nonBLB_parallel_legacy_trace
Rcpp::List loglikelihood_nonBLB_parallel_legacy_trace(const arma::mat& y, const arma::mat& covariates, const arma::mat& age2, const arma::mat& age3, const arma::mat& age4, const arma::mat& tin2, const arma::mat& tin3, const arma::mat& X, const arma::vec& initial, const arma::vec& first, int L, const arma::mat& combins, const arma::vec& params);
RcppExport SEXP _overcoverage2_loglikelihood_nonBLB_parallel_legacy_trace(SEXP ySEXP, SEXP covariatesSEXP, SEXP age2SEXP, SEXP age3SEXP, SEXP age4SEXP, SEXP tin2SEXP, SEXP tin3SEXP, SEXP XSEXP, SEXP initialSEXP, SEXP firstSEXP, SEXP LSEXP, SEXP combinsSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type covariates(covariatesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age2(age2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age3(age3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age4(age4SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tin2(tin2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tin3(tin3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type initial(initialSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type combins(combinsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(loglikelihood_nonBLB_parallel_legacy_trace(y, covariates, age2, age3, age4, tin2, tin3, X, initial, first, L, combins, params));
    return rcpp_result_gen;
END_RCPP
}
// loglikelihood_nonBLB_parallel_legacy_trace_parallel
Rcpp::List loglikelihood_nonBLB_parallel_legacy_trace_parallel(const arma::mat& y, const arma::mat& covariates, const arma::mat& age2, const arma::mat& age3, const arma::mat& age4, const arma::mat& tin2, const arma::mat& tin3, const arma::mat& X, const arma::vec& initial, const arma::vec& first, int L, const arma::mat& combins, const arma::vec& params);
RcppExport SEXP _overcoverage2_loglikelihood_nonBLB_parallel_legacy_trace_parallel(SEXP ySEXP, SEXP covariatesSEXP, SEXP age2SEXP, SEXP age3SEXP, SEXP age4SEXP, SEXP tin2SEXP, SEXP tin3SEXP, SEXP XSEXP, SEXP initialSEXP, SEXP firstSEXP, SEXP LSEXP, SEXP combinsSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type covariates(covariatesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age2(age2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age3(age3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age4(age4SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tin2(tin2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tin3(tin3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type initial(initialSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type combins(combinsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(loglikelihood_nonBLB_parallel_legacy_trace_parallel(y, covariates, age2, age3, age4, tin2, tin3, X, initial, first, L, combins, params));
    return rcpp_result_gen;
END_RCPP
}
// mixing_probs
NumericMatrix mixing_probs(const arma::mat& y, const arma::mat& covariates, const arma::mat& age2, const arma::mat& age3, const arma::mat& age4, const arma::mat& tin2, const arma::mat& tin3, const arma::mat& X, const arma::vec& initial, const arma::vec& first, int L, const arma::mat& combins, const arma::vec& params);
RcppExport SEXP _overcoverage2_mixing_probs(SEXP ySEXP, SEXP covariatesSEXP, SEXP age2SEXP, SEXP age3SEXP, SEXP age4SEXP, SEXP tin2SEXP, SEXP tin3SEXP, SEXP XSEXP, SEXP initialSEXP, SEXP firstSEXP, SEXP LSEXP, SEXP combinsSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type covariates(covariatesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age2(age2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age3(age3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age4(age4SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tin2(tin2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tin3(tin3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type initial(initialSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type combins(combinsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(mixing_probs(y, covariates, age2, age3, age4, tin2, tin3, X, initial, first, L, combins, params));
    return rcpp_result_gen;
END_RCPP
}
// viterbi
NumericMatrix viterbi(const arma::mat& y, const arma::mat& covariates, const arma::mat& age2, const arma::mat& age3, const arma::mat& age4, const arma::mat& tin2, const arma::mat& tin3, const arma::mat& combins, const arma::mat& X, const arma::vec& initial, const arma::vec& first, int L, const arma::vec& params, const arma::mat& mixing);
RcppExport SEXP _overcoverage2_viterbi(SEXP ySEXP, SEXP covariatesSEXP, SEXP age2SEXP, SEXP age3SEXP, SEXP age4SEXP, SEXP tin2SEXP, SEXP tin3SEXP, SEXP combinsSEXP, SEXP XSEXP, SEXP initialSEXP, SEXP firstSEXP, SEXP LSEXP, SEXP paramsSEXP, SEXP mixingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type covariates(covariatesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age2(age2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age3(age3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type age4(age4SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tin2(tin2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tin3(tin3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type combins(combinsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type initial(initialSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type first(firstSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mixing(mixingSEXP);
    rcpp_result_gen = Rcpp::wrap(viterbi(y, covariates, age2, age3, age4, tin2, tin3, combins, X, initial, first, L, params, mixing));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_overcoverage2_loglikelihood_ultrafast", (DL_FUNC) &_overcoverage2_loglikelihood_ultrafast, 15},
    {"_overcoverage2_loglikelihood_cpp", (DL_FUNC) &_overcoverage2_loglikelihood_cpp, 15},
    {"_overcoverage2_loglikelihood_fast_cpp", (DL_FUNC) &_overcoverage2_loglikelihood_fast_cpp, 15},
    {"_overcoverage2_loglikelihood_BLB_parallel", (DL_FUNC) &_overcoverage2_loglikelihood_BLB_parallel, 15},
    {"_overcoverage2_loglikelihood_BLB_parallel_legacy", (DL_FUNC) &_overcoverage2_loglikelihood_BLB_parallel_legacy, 15},
    {"_overcoverage2_loglikelihood_nonBLB_parallel", (DL_FUNC) &_overcoverage2_loglikelihood_nonBLB_parallel, 13},
    {"_overcoverage2_loglikelihood_nonBLB_parallel_legacy", (DL_FUNC) &_overcoverage2_loglikelihood_nonBLB_parallel_legacy, 13},
    {"_overcoverage2_loglikelihood_nonBLB_parallel_legacy_debug", (DL_FUNC) &_overcoverage2_loglikelihood_nonBLB_parallel_legacy_debug, 13},
    {"_overcoverage2_loglikelihood_nonBLB_input_debug", (DL_FUNC) &_overcoverage2_loglikelihood_nonBLB_input_debug, 12},
    {"_overcoverage2_loglikelihood_nonBLB_deep_debug", (DL_FUNC) &_overcoverage2_loglikelihood_nonBLB_deep_debug, 9},
    {"_overcoverage2_loglikelihood_nonBLB_parallel_legacy_trace", (DL_FUNC) &_overcoverage2_loglikelihood_nonBLB_parallel_legacy_trace, 13},
    {"_overcoverage2_loglikelihood_nonBLB_parallel_legacy_trace_parallel", (DL_FUNC) &_overcoverage2_loglikelihood_nonBLB_parallel_legacy_trace_parallel, 13},
    {"_overcoverage2_mixing_probs", (DL_FUNC) &_overcoverage2_mixing_probs, 13},
    {"_overcoverage2_viterbi", (DL_FUNC) &_overcoverage2_viterbi, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_overcoverage2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
