name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      R_PROFILE_USER: /dev/null
      R_PROFILE_SITE: /dev/null
      R_ENVIRON_USER: /dev/null
      R_ENVIRON_SITE: /dev/null

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: "release", cran: true}
          - {os: windows-latest, r: "release", cran: false}
          - {os: macos-latest, r: "release", cran: false}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libtbb-dev

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install RcppParallel system libs
        if: runner.os == 'Linux'
        run: Rscript -e 'install.packages("RcppParallel", type = "source", repos = "https://cloud.r-project.org")'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: ${{ matrix.config.cran && 'c("--no-manual", "--as-cran")' || 'c("--no-manual")' }}
          build_args: 'c("--no-manual")'
